### ISSUE TITLE
Host packages on the Fedora Copr

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rpm-specs-gaming#3]
Work has been started here: https://copr.fedorainfracloud.org/coprs/ekultails/gaming/

But I have ran into some issues which I have documented here: https://github.com/LukeShortCloud/rootpages/issues/967

**Comment by LukeShortCloud** [comment]
I believe the best past forward is to create a GitHub Actions CI/CD pipeline to build a source RPM and publish it to the Fedora Copr to build. This should happen every time there is a push to the `main` branch. Other branches should have a CI pipeline to build the source RPM, then the binary RPM, and finally install it. All within a Fedora container.

**Comment by LukeShortCloud** [comment]
I'm running into lots of issues using GitHub Actions that I'll document here. Most, if not all, seem to be bugs and limitations of GitHub Actions itself.

1. Using `on.workflow_run.workflows` only works when the GitHub Actions for the workflow using that is in the default branch. Temporarily, I switched our default branch from "main" to "github_actions" for testing purposes. I do not want to merge this CI/CD pipeline until it is finished. Refer to: `https://github.com/github/docs/issues/799`.
2. Using `on.workflow_run.workflows` and `on.push.paths` together does not work. The paths are ignored completely which leads to the jobs running even if no files from that path were changed.

```
 ---
 name: Upload gamescope-session source RPM
 on:
  push:
    paths:
      - 'gamescope-session/**'
  workflow_run:
    workflows:
      - 'Build all RPMs'
    branches:
      # TODO: Switch to 'main' before merging.
      - github_actions
    types:
      - completed
jobs:
  upload:
    name: Upload gamescope-session source RPM to Fedora Copr
    runs-on: ubuntu-20.04
    container:
      image: fedora:38
    # If the GitHub Actions workflow to build the RPMs succeeds,
    # then upload the SRPM to Fedora Copr.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Dummy output
         run: true
```

3. Using a third-party filter to see if a file changes fails due to a bug in their plugin. Refer to: `https://github.com/dorny/paths-filter/issues/88`.

```
---
name: Upload gamescope-session source RPM
on:
  workflow_run:
    workflows:
      - 'Build all RPMs'
    branches:
      # TODO: Switch to 'main' before merging.
      - github_actions
    types:
      - completed
jobs:
  upload:
    name: Upload gamescope-session source RPM to Fedora Copr
    runs-on: ubuntu-20.04
    container:
      image: fedora:38
    # If the GitHub Actions workflow to build the RPMs succeeds,
    # then upload the SRPM to Fedora Copr.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Tested with both v2 and v3.
      - uses: actions/checkout@v3
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Install 'git' for paths-filter to work
        run: dnf -y install git
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            gamescope-session:
              - 'gamescope-session/**'
      - name: Dummy output
        if: steps.changes.outputs.gamescope-session == 'true'
         run: true
```

Error:

```
Get current git ref
  /usr/bin/git branch --show-current
  fatal: not a git repository (or any parent up to mount point /)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Error: The process '/usr/bin/git' failed with exit code [12](https://github.com/LukeShortCloud/rpm-specs-gaming/actions/runs/4845851893/jobs/8635015769#step:5:13)8
```
